"""create pokemon table

Revision ID: be778d94911f
Revises: 7943a15e06fd
Create Date: 2022-10-13 14:14:31.973698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be778d94911f'
down_revision = '7943a15e06fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('moves', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'moves')
    # ### end Alembic commands ###
